// packages/shaders-react/src/shaders/neuro-noise.tsx
import { useMemo } from 'react';
import { ShaderMount, type ShaderMountProps } from '../shader-mount';
import { getShaderColorFromString, neuroNoiseFragmentShader, type NeuroNoiseUniforms } from '@paper-design/shaders';

export type NeuroNoiseParams = {
  colorFront?: string;
  colorBack?: string;
  scale?: number;
  speed?: number;
  brightness?: number;
};

export type NeuroNoiseProps = Omit<ShaderMountProps, 'fragmentShader'> & NeuroNoiseParams;

type NeuroNoisePreset = { name: string; params: Required<NeuroNoiseParams> };

export const defaultPreset: NeuroNoisePreset = {
  name: 'Default',
  params: {
    colorFront: 'rgba(195, 163, 255, 1)',
    colorBack: 'rgba(0, 0, 0, 1)',
    scale: 0.7,
    speed: 1,
    brightness: 1.3,
  },
} as const;

const marblePreset: NeuroNoisePreset = {
  name: 'Marble',
  params: {
    colorFront: 'rgba(29, 32, 47, 1)',
    colorBack: 'rgba(247, 247, 247, 1)',
    scale: 1.2,
    speed: 0,
    brightness: 1.1,
  },
} as const;

export const neuroNoisePresets: NeuroNoisePreset[] = [defaultPreset, marblePreset] as const;

export const NeuroNoise = (props: NeuroNoiseProps): JSX.Element => {
  const uniforms: NeuroNoiseUniforms = useMemo(() => {
    return {
      u_colorFront: getShaderColorFromString(props.colorFront, defaultPreset.params.colorFront),
      u_colorBack: getShaderColorFromString(props.colorBack, defaultPreset.params.colorBack),
      u_scale: props.scale ?? defaultPreset.params.scale,
      u_speed: props.speed ?? defaultPreset.params.speed,
      u_brightness: props.brightness ?? defaultPreset.params.brightness,
    };
  }, [props.colorFront, props.colorBack, props.scale, props.speed, props.brightness]);

  return <ShaderMount {...props} fragmentShader={neuroNoiseFragmentShader} uniforms={uniforms} />;
};

// packages/shaders-vue/src/shaders/neuro-noise.vue
<script lang="ts">
import { computed } from 'vue';
import ShaderMount, { type GlobalParams, type ShaderMountProps } from '../shader-mount.vue';
import { getShaderColorFromString, neuroNoiseFragmentShader, type NeuroNoiseUniforms } from '@paper-design/shaders';

export type NeuroNoiseParams = {
  colorFront?: string;
  colorBack?: string;
  scale?: number;
  brightness?: number;
} & GlobalParams;

export type NeuroNoiseProps = Omit<ShaderMountProps, 'fragmentShader'> & NeuroNoiseParams;

type NeuroNoisePreset = { name: string; params: Required<NeuroNoiseParams> };

export const defaultPreset: NeuroNoisePreset = {
  name: 'Default',
  params: {
    colorFront: 'hsla(261, 100%, 82%, 1)',
    colorBack: 'hsla(0, 0%, 0%, 1)',
    scale: 0.7,
    speed: 1,
    brightness: 1.3,
    seed: 0,
  },
} as const;

const marblePreset: NeuroNoisePreset = {
  name: 'Marble',
  params: {
    // Note: Keep default colors in HSLA format so that our Leva controls show a transparency channel (rgba and hex8 do not work)
    colorFront: 'hsla(230, 24%, 15%, 1)',
    colorBack: 'hsla(0, 0%, 97%, 1)',
    scale: 1.2,
    speed: 0,
    brightness: 1.1,
    seed: 0,
  },
} as const;

export const neuroNoisePresets: NeuroNoisePreset[] = [defaultPreset, marblePreset] as const;
</script>

<script setup lang="ts">
const props = defineProps<NeuroNoiseProps>();

const uniforms = computed<NeuroNoiseUniforms>(() => {
  return {
    u_colorFront: getShaderColorFromString(props.colorFront, defaultPreset.params.colorFront),
    u_colorBack: getShaderColorFromString(props.colorBack, defaultPreset.params.colorBack),
    u_scale: props.scale ?? defaultPreset.params.scale,
    u_speed: props.speed ?? defaultPreset.params.speed,
    u_brightness: props.brightness ?? defaultPreset.params.brightness,
    u_seed: props.seed ?? defaultPreset.params.seed,
  };
});
</script>

<template>
  <ShaderMount v-bind="props" :fragment-shader="neuroNoiseFragmentShader" :uniforms />
</template>
